// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskDocumentQuestion(arg1, arg2) {
  return window['go']['main']['App']['AskDocumentQuestion'](arg1, arg2);
}

export function CheckUserPermission(arg1, arg2) {
  return window['go']['main']['App']['CheckUserPermission'](arg1, arg2);
}

export function CompleteFirstTimeSetup(arg1, arg2) {
  return window['go']['main']['App']['CompleteFirstTimeSetup'](arg1, arg2);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function GenerateDescriptionFromText(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDescriptionFromText'](arg1, arg2, arg3);
}

export function GenerateDocumentSummary(arg1, arg2) {
  return window['go']['main']['App']['GenerateDocumentSummary'](arg1, arg2);
}

export function GenerateDocumentTags(arg1, arg2) {
  return window['go']['main']['App']['GenerateDocumentTags'](arg1, arg2);
}

export function GenerateTagsFromText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateTagsFromText'](arg1, arg2, arg3, arg4);
}

export function GetActivityStatistics() {
  return window['go']['main']['App']['GetActivityStatistics']();
}

export function GetAllDocuments() {
  return window['go']['main']['App']['GetAllDocuments']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDocumentByID(arg1) {
  return window['go']['main']['App']['GetDocumentByID'](arg1);
}

export function GetDocumentPermissions(arg1) {
  return window['go']['main']['App']['GetDocumentPermissions'](arg1);
}

export function GetDocumentReportResults() {
  return window['go']['main']['App']['GetDocumentReportResults']();
}

export function GetDocumentStatistics() {
  return window['go']['main']['App']['GetDocumentStatistics']();
}

export function GetDocumentTags(arg1) {
  return window['go']['main']['App']['GetDocumentTags'](arg1);
}

export function GetDocumentTrends(arg1) {
  return window['go']['main']['App']['GetDocumentTrends'](arg1);
}

export function GetDocumentVersions(arg1) {
  return window['go']['main']['App']['GetDocumentVersions'](arg1);
}

export function GetDocumentsByType() {
  return window['go']['main']['App']['GetDocumentsByType']();
}

export function GetDocumentsForUser() {
  return window['go']['main']['App']['GetDocumentsForUser']();
}

export function GetRecentActivity(arg1) {
  return window['go']['main']['App']['GetRecentActivity'](arg1);
}

export function GetTopContributors(arg1) {
  return window['go']['main']['App']['GetTopContributors'](arg1);
}

export function GetUserDocumentCount() {
  return window['go']['main']['App']['GetUserDocumentCount']();
}

export function GetUserDocumentSize() {
  return window['go']['main']['App']['GetUserDocumentSize']();
}

export function GetUserProjects() {
  return window['go']['main']['App']['GetUserProjects']();
}

export function LogActivity(arg1) {
  return window['go']['main']['App']['LogActivity'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function RemoveDocumentPermission(arg1, arg2) {
  return window['go']['main']['App']['RemoveDocumentPermission'](arg1, arg2);
}

export function SetDocumentPermission(arg1) {
  return window['go']['main']['App']['SetDocumentPermission'](arg1);
}

export function SetOpenAIKey(arg1) {
  return window['go']['main']['App']['SetOpenAIKey'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UpdateDocument(arg1, arg2) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2);
}

export function UploadDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3);
}
