// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AskDocumentQuestion(arg1:number,arg2:string):Promise<string>;

export function CheckUserPermission(arg1:number,arg2:string):Promise<boolean>;

export function CompleteFirstTimeSetup(arg1:string,arg2:string):Promise<Record<string, any>>;

export function CreateProject(arg1:models.Projekti):Promise<void>;

export function CreateUser(arg1:models.Korisnici,arg2:string):Promise<void>;

export function DeleteDocument(arg1:number):Promise<void>;

export function GenerateDescriptionFromText(arg1:string,arg2:string,arg3:string):Promise<string>;

export function GenerateDocumentSummary(arg1:number,arg2:number):Promise<string>;

export function GenerateDocumentTags(arg1:number,arg2:number):Promise<Array<string>>;

export function GenerateTagsFromText(arg1:string,arg2:string,arg3:string,arg4:number):Promise<Array<string>>;

export function GetActivityStatistics():Promise<Array<models.StatistikaAktivnosti>>;

export function GetAllDocuments():Promise<Array<models.Dokumenti>>;

export function GetAllTags():Promise<Array<models.Tagovi>>;

export function GetAllUsers():Promise<Array<models.Korisnici>>;

export function GetCurrentUser():Promise<models.Korisnici>;

export function GetDocumentByID(arg1:number):Promise<models.Dokumenti>;

export function GetDocumentPermissions(arg1:number):Promise<Array<models.DocumentPermissionResponse>>;

export function GetDocumentStatistics():Promise<models.StatistikaDokumenata>;

export function GetDocumentTags(arg1:number):Promise<Array<models.Tagovi>>;

export function GetDocumentTrends(arg1:number):Promise<Array<Record<string, any>>>;

export function GetDocumentVersions(arg1:number):Promise<Array<models.VerzijeDokumenata>>;

export function GetDocumentsByType():Promise<Record<string, number>>;

export function GetRecentActivity(arg1:number):Promise<Array<models.SkornjeAktivnosti>>;

export function GetTopContributors(arg1:number):Promise<Array<Record<string, any>>>;

export function GetUserProjects():Promise<Array<models.Projekti>>;

export function LogActivity(arg1:models.ActivityLogRequest):Promise<void>;

export function Login(arg1:string,arg2:string):Promise<services.LoginResponse>;

export function Logout():Promise<void>;

export function RemoveDocumentPermission(arg1:number,arg2:number):Promise<void>;

export function SetDocumentPermission(arg1:models.DocumentPermissionRequest):Promise<void>;

export function SetOpenAIKey(arg1:string):Promise<void>;

export function TestConnection():Promise<Record<string, any>>;

export function UpdateDocument(arg1:number,arg2:models.UploadDocumentRequest):Promise<void>;

export function UploadDocument(arg1:models.UploadDocumentRequest,arg2:Array<number>,arg3:string):Promise<number>;
