// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProjectMember(arg1, arg2) {
  return window['go']['main']['App']['AddProjectMember'](arg1, arg2);
}

export function AddTaskComment(arg1, arg2) {
  return window['go']['main']['App']['AddTaskComment'](arg1, arg2);
}

export function ApprovePhaseChangeRequest(arg1) {
  return window['go']['main']['App']['ApprovePhaseChangeRequest'](arg1);
}

export function AskDocumentQuestion(arg1, arg2) {
  return window['go']['main']['App']['AskDocumentQuestion'](arg1, arg2);
}

export function CheckUserPermission(arg1, arg2) {
  return window['go']['main']['App']['CheckUserPermission'](arg1, arg2);
}

export function CloneWorkflow(arg1, arg2) {
  return window['go']['main']['App']['CloneWorkflow'](arg1, arg2);
}

export function CompleteFirstTimeSetup(arg1, arg2) {
  return window['go']['main']['App']['CompleteFirstTimeSetup'](arg1, arg2);
}

export function CompleteProject(arg1) {
  return window['go']['main']['App']['CompleteProject'](arg1);
}

export function CreateCondition(arg1) {
  return window['go']['main']['App']['CreateCondition'](arg1);
}

export function CreateNewProject(arg1) {
  return window['go']['main']['App']['CreateNewProject'](arg1);
}

export function CreateOrUpdateConditionAssessment(arg1) {
  return window['go']['main']['App']['CreateOrUpdateConditionAssessment'](arg1);
}

export function CreatePhase(arg1) {
  return window['go']['main']['App']['CreatePhase'](arg1);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function CreateTask(arg1) {
  return window['go']['main']['App']['CreateTask'](arg1);
}

export function CreateUser(arg1, arg2) {
  return window['go']['main']['App']['CreateUser'](arg1, arg2);
}

export function CreateWorkflow(arg1) {
  return window['go']['main']['App']['CreateWorkflow'](arg1);
}

export function DeleteCondition(arg1) {
  return window['go']['main']['App']['DeleteCondition'](arg1);
}

export function DeleteDocument(arg1) {
  return window['go']['main']['App']['DeleteDocument'](arg1);
}

export function DeletePhase(arg1) {
  return window['go']['main']['App']['DeletePhase'](arg1);
}

export function DeleteProject(arg1) {
  return window['go']['main']['App']['DeleteProject'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['main']['App']['DeleteTask'](arg1);
}

export function DeleteWorkflow(arg1) {
  return window['go']['main']['App']['DeleteWorkflow'](arg1);
}

export function GenerateDescriptionFromText(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateDescriptionFromText'](arg1, arg2, arg3);
}

export function GenerateDocumentSummary(arg1, arg2) {
  return window['go']['main']['App']['GenerateDocumentSummary'](arg1, arg2);
}

export function GenerateDocumentTags(arg1, arg2) {
  return window['go']['main']['App']['GenerateDocumentTags'](arg1, arg2);
}

export function GenerateTagsFromText(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GenerateTagsFromText'](arg1, arg2, arg3, arg4);
}

export function GetActivityStatistics() {
  return window['go']['main']['App']['GetActivityStatistics']();
}

export function GetAllDocuments() {
  return window['go']['main']['App']['GetAllDocuments']();
}

export function GetAllOverdueTasks() {
  return window['go']['main']['App']['GetAllOverdueTasks']();
}

export function GetAllProjects() {
  return window['go']['main']['App']['GetAllProjects']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAllUsers() {
  return window['go']['main']['App']['GetAllUsers']();
}

export function GetAllWorkflows() {
  return window['go']['main']['App']['GetAllWorkflows']();
}

export function GetAvailableTeamMembers() {
  return window['go']['main']['App']['GetAvailableTeamMembers']();
}

export function GetConditionAssessmentsByTask(arg1) {
  return window['go']['main']['App']['GetConditionAssessmentsByTask'](arg1);
}

export function GetConditionFulfillmentStatus(arg1) {
  return window['go']['main']['App']['GetConditionFulfillmentStatus'](arg1);
}

export function GetConditionsByPhase(arg1) {
  return window['go']['main']['App']['GetConditionsByPhase'](arg1);
}

export function GetCurrentUser() {
  return window['go']['main']['App']['GetCurrentUser']();
}

export function GetDocumentByID(arg1) {
  return window['go']['main']['App']['GetDocumentByID'](arg1);
}

export function GetDocumentPermissions(arg1) {
  return window['go']['main']['App']['GetDocumentPermissions'](arg1);
}

export function GetDocumentStatistics() {
  return window['go']['main']['App']['GetDocumentStatistics']();
}

export function GetDocumentTags(arg1) {
  return window['go']['main']['App']['GetDocumentTags'](arg1);
}

export function GetDocumentTrends(arg1) {
  return window['go']['main']['App']['GetDocumentTrends'](arg1);
}

export function GetDocumentVersions(arg1) {
  return window['go']['main']['App']['GetDocumentVersions'](arg1);
}

export function GetDocumentsByType() {
  return window['go']['main']['App']['GetDocumentsByType']();
}

export function GetOverdueTasksForProject(arg1) {
  return window['go']['main']['App']['GetOverdueTasksForProject'](arg1);
}

export function GetPhaseChangeRequestsForProject(arg1) {
  return window['go']['main']['App']['GetPhaseChangeRequestsForProject'](arg1);
}

export function GetPhaseChangeRequestsForTask(arg1) {
  return window['go']['main']['App']['GetPhaseChangeRequestsForTask'](arg1);
}

export function GetProjectAnalytics(arg1) {
  return window['go']['main']['App']['GetProjectAnalytics'](arg1);
}

export function GetProjectByID(arg1) {
  return window['go']['main']['App']['GetProjectByID'](arg1);
}

export function GetProjectMembers(arg1) {
  return window['go']['main']['App']['GetProjectMembers'](arg1);
}

export function GetProjectResources(arg1) {
  return window['go']['main']['App']['GetProjectResources'](arg1);
}

export function GetProjectsByCurrentUser() {
  return window['go']['main']['App']['GetProjectsByCurrentUser']();
}

export function GetProjectsByStatus(arg1) {
  return window['go']['main']['App']['GetProjectsByStatus'](arg1);
}

export function GetRecentActivity(arg1) {
  return window['go']['main']['App']['GetRecentActivity'](arg1);
}

export function GetTaskByID(arg1) {
  return window['go']['main']['App']['GetTaskByID'](arg1);
}

export function GetTaskComments(arg1) {
  return window['go']['main']['App']['GetTaskComments'](arg1);
}

export function GetTasksByCurrentUser() {
  return window['go']['main']['App']['GetTasksByCurrentUser']();
}

export function GetTasksByPhase(arg1) {
  return window['go']['main']['App']['GetTasksByPhase'](arg1);
}

export function GetTasksByProject(arg1) {
  return window['go']['main']['App']['GetTasksByProject'](arg1);
}

export function GetTasksByUser(arg1) {
  return window['go']['main']['App']['GetTasksByUser'](arg1);
}

export function GetTopContributors(arg1) {
  return window['go']['main']['App']['GetTopContributors'](arg1);
}

export function GetUserProjects() {
  return window['go']['main']['App']['GetUserProjects']();
}

export function GetWorkflowByID(arg1) {
  return window['go']['main']['App']['GetWorkflowByID'](arg1);
}

export function GetWorkflowPhases(arg1) {
  return window['go']['main']['App']['GetWorkflowPhases'](arg1);
}

export function GetWorkflowTemplates() {
  return window['go']['main']['App']['GetWorkflowTemplates']();
}

export function LogActivity(arg1) {
  return window['go']['main']['App']['LogActivity'](arg1);
}

export function Login(arg1, arg2) {
  return window['go']['main']['App']['Login'](arg1, arg2);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function MoveTaskToPhase(arg1, arg2) {
  return window['go']['main']['App']['MoveTaskToPhase'](arg1, arg2);
}

export function RejectPhaseChangeRequest(arg1) {
  return window['go']['main']['App']['RejectPhaseChangeRequest'](arg1);
}

export function RemoveDocumentPermission(arg1, arg2) {
  return window['go']['main']['App']['RemoveDocumentPermission'](arg1, arg2);
}

export function RemoveProjectMember(arg1, arg2) {
  return window['go']['main']['App']['RemoveProjectMember'](arg1, arg2);
}

export function RequestPhaseChange(arg1, arg2, arg3) {
  return window['go']['main']['App']['RequestPhaseChange'](arg1, arg2, arg3);
}

export function SetDocumentPermission(arg1) {
  return window['go']['main']['App']['SetDocumentPermission'](arg1);
}

export function SetOpenAIKey(arg1) {
  return window['go']['main']['App']['SetOpenAIKey'](arg1);
}

export function TestConnection() {
  return window['go']['main']['App']['TestConnection']();
}

export function UpdateCondition(arg1) {
  return window['go']['main']['App']['UpdateCondition'](arg1);
}

export function UpdateDocument(arg1, arg2) {
  return window['go']['main']['App']['UpdateDocument'](arg1, arg2);
}

export function UpdatePhase(arg1, arg2) {
  return window['go']['main']['App']['UpdatePhase'](arg1, arg2);
}

export function UpdateProject(arg1, arg2) {
  return window['go']['main']['App']['UpdateProject'](arg1, arg2);
}

export function UpdateTask(arg1, arg2) {
  return window['go']['main']['App']['UpdateTask'](arg1, arg2);
}

export function UpdateTaskProgress(arg1, arg2) {
  return window['go']['main']['App']['UpdateTaskProgress'](arg1, arg2);
}

export function UpdateWorkflow(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1, arg2);
}

export function UploadDocument(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadDocument'](arg1, arg2, arg3);
}
